version: '3'

services:

  mongo:
    image: mongo
    restart: always

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081

  my-app:
    build: .
    ports:
      - "3000:3000"

# docker-compose up
# docker-compose up --build
# docker-compose up --build --force-recreate --renew-anon-volumes